version: '3.4'

networks:
  ratelimit-dev:
    driver: bridge

services:
  ratelimit:
    image: ${DOCKER_REGISTRY-}ratelimit
    build:
      context: .
      dockerfile: RateLimit/Dockerfile
    ports:
      - "8000:80"
    networks:
      - ratelimit-dev
